# version: '3'

# services:
#   # Service MariaDB
#   mariadb:
#     container_name: mariadb
#     networks:
#       - inception
#     build:
#       context: requirements/mariadb
#       dockerfile: Dockerfile
#     env_file: .env
#     volumes:
#       - mariadb:/var/lib/mysql
#     restart: unless-stopped
#     expose:
#       - "3306"

#   # Service Nginx
#   nginx:
#     container_name: nginx
#     volumes:
#       - wordpress:/var/www/wordpress
#     networks:
#       - inception
#     depends_on:
#       - wordpress
#     build:
#       context: requirements/nginx
#       dockerfile: Dockerfile
#     env_file: .env
#     ports:
#       - "443:443"  # Nginx exposé sur le port 443
#     restart: on-failure

#   # Service WordPress
#   wordpress:
#     container_name: wordpress
#     env_file: .env
#     volumes:
#       - wordpress:/var/www/wordpress
#     networks:
#       - inception
#     build:
#       context: requirements/wordpress
#       dockerfile: Dockerfile
#     depends_on:
#       - mariadb
#     restart: on-failure
#     expose:
#       - "9000"

# # Volumes pour persister les données
# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/Users/login/data/wordpress'  # Modifier en fonction de ton système
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/Users/login/data/mariadb'  # Modifier en fonction de ton système

# # Réseau pour permettre la communication entre les containers
# networks:
#   inception:
#     driver: bridge
